# Testing Script for Sudoku

# Outline of Testing Cases TODO
# 1. Invalid parameters passed to sudoku
# 2. Ask creator to create a puzzle
# 3. Invalid stdin format passed to sudoku solve. Expect error msg.
# 4. Ask solver to solve a pre-set puzzle with a unique solution, and compare output, expecting the same output as the solution.
# 5. Ask solver to solve a pre-set puzzle with multiple solutions, and compare output of first solution found, as well as noting that our program detected multiple solutions.
# 6. Ask solver to solve a pre-set puzzle with no solutions, our program should tell us "no solutions".
# 7. Invalid puzzle passed to sudoku solve (right off the bat, there are multiple numbers in the same row/col/grid). Expect error msg.
# 8. 'n' fuzztests generated by creator - all should generate unique solutions 

# Please note, all tests generated with DEBUG flag on solver enabled, but not on creator.
